### ISSUE TITLE
Interpreting DRAMSim2 results (only 8 banks?)

### ISSUE THREAD

**Issue by konbick** [umd-memsys/DRAMSim2#69]
Hi,

I assume that the bank's power consumption refer to all a certain bank in all DRAM devices, is that correct?

E.g. bank0 includes the power consumption of bank0 in all devices.

Just want to verify this.

Thanks
Kon

**Comment by shavvn** [comment]
Hi @konbick ,

Yes you're correct. But also note it's all devices in a rank.
