### ISSUE TITLE
Power calculation in MemoryController.cpp

### ISSUE THREAD

**Issue by konbick** [umd-memsys/DRAMSim2#70]
Hi,

before power stats are printed in the MemoryController.cpp file, the energy is divided by cyclesElapsed. However, cyclesElapsed doesn't have the unit of [s]. I'd expect to see cyclesElapsed*clockPeriod or something like that. So I guess the power stats are relative to something (clock cycle?) but I don't get exactly what they tell me. Could you clarify?

Thanks a lot
Kon

**Comment by shavvn** [comment]
the final calculation takes into account of the clockPeriod (e.g. line 866-870 in MemoryController.cpp) so that we only have  to do it once instead of each time some energy is incremented.
