### ISSUE TITLE
delay calculate bug!

### ISSUE THREAD

**Issue by Cassiel-girl** [umd-memsys/DRAMSim2#72]
First, The transaction is added in cpu clock.  
Source code: transactionReceiver.add_pending(*trans, i); in TraceBasedSim.cpp
Second, But the transaction is getted in dram clock.
void read_complete(unsigned id, uint64_t address, uint64_t done_cycle) in TraceBasedSim.cpp
Third, calculate delay using the two number
uint64_t latency = done_cycle - added_cycle;
So, Is this correctly? Why not using the same clock？

**Comment by shavvn** [comment]
all the cycles here are DRAM cycles, so  they're the same clock.
