### ISSUE TITLE
Generating physical address trace of a program

### ISSUE THREAD

**Issue by sarabjeetsingh007** [umd-memsys/DRAMSim2#73]
Hi,
I see that DRAMSim2 provides an in-depth simulation of the main memory, but requires a physical address trace of the program as the input. How to generate these physical address traces of an application, as most tools provide ways to generate virtual address traces, not physical.

**Comment by shavvn** [comment]
You can use a CPU simulator that simulates a TLB (the unit that does the VA->PA translation) to generate physical address. For example, Gem5.

**Comment by licaiwei397** [comment]
> You can use a CPU simulator that simulates a TLB (the unit that does the VA->PA translation) to generate physical address. For example, Gem5.

dear shavvn,do you know how to generate a physical trace file with gpgpu-sim,thank you very much
