### ISSUE TITLE
How to generate the *.trc.gz trace files?

### ISSUE THREAD

**Issue by HaFred** [umd-memsys/DRAMSim2#80]
Hi, does anyone happen to know how do we generate the *.trc.gz trace files?
Say I have a .riscv compiled binaries in which some of the instructions are for DRAM access, how do I do this?
Thanks~

**Comment by he238** [comment]
I tried to do this with GEM5. You modify the memory of GEM5 to record the access trace.

**Comment by HaFred** [comment]
> I tried to do this with GEM5. You modify the memory of GEM5 to record the access trace.

Hi thank you for your reply. Could you provide a minimum gem5 command for integrate dramsim2? I searched around but did not find any...
